# Generated by Django 2.0.13 on 2019-04-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='orginizer',
            new_name='organizer',
        ),
    ]
