# Generated by Django 2.0.13 on 2019-04-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('gender', models.NullBooleanField(choices=[(True, 'Male'), (False, 'Famale')])),
                ('birthday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birthmonth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birthyear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('karma', models.PositiveSmallIntegerField(default=0, null=True)),
                ('login_count', models.PositiveSmallIntegerField(default=0, null=True)),
                ('locale', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True)),
                ('social', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='profiles.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
