# Generated by Django 2.0.13 on 2019-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_auto_20190408_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='url',
            field=models.URLField(max_length=150),
        ),
    ]
