# Generated by Django 2.0.13 on 2019-04-08 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190408_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hack', '0005_hackathon_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orginizer',
            new_name='Organizer',
        ),
    ]
