# Generated by Django 2.0.13 on 2019-04-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0006_auto_20190408_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=255)),
                ('github', models.URLField()),
                ('presentation', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('status', models.SmallIntegerField(choices=[(0, 'Team NOT ready'), (1, 'Team ready!'), (-1, 'excluded')], db_index=True, default=0, verbose_name='Статус команды')),
                ('progress', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hacker',
            name='github',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leader', to='hack.Hacker'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='hack.Hacker'),
        ),
    ]
