# Generated by Django 2.0.13 on 2019-04-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0008_auto_20190408_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('prize', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AddField(
            model_name='nomination',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hack.Hackathon'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hack.Sponsor'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='teams',
            field=models.ManyToManyField(blank=True, to='hack.Team'),
        ),
    ]
